# Generated by Django 6.0.4 on 2026-05-04 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cellphone', models.CharField(max_length=10, unique=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('nss', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teachers',
                'managed': True,
            },
        ),
    ]
